nodeLinker: node-modules

npmRegistries:
    //npm.fontawesome.com:
        npmAlwaysAuth: true
        npmAuthToken: 3BC86CFA-251A-4F74-AA8D-482FB3AA140F

npmScopes:
    fortawesome:
        npmRegistryServer: https://npm.fontawesome.com/
