import { Group, Stack, Title } from "@mantine/core";
import Head from "next/head";
import { useUser } from "@auth0/nextjs-auth0";
import { LayoutShellSideNav } from "layouts";
import { ReactElement } from "react";
import { useGetMe } from "@data/user/hooks";

function Home() {
    return (
        <>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Group
                grow
                sx={(theme) => ({
                    padding: theme.spacing.md,
                })}
            >
                <Stack>
                    <Group>
                        <Title order={1} sx={{ fontSize: 64 }}>
                            Dashboard
                        </Title>
                    </Group>
                </Stack>
            </Group>
        </>
    );
}

Home.getLayout = function getLayout(page: ReactElement) {
    //return <LayoutShellSideNav>{page}</LayoutShellSideNav>;
    return page;
};

export default Home;
