import OlViewer from '@components/ui/olZoom'
import { Group, Stack, Title } from '@mantine/core'
import Head from 'next/head'
import { ReactElement } from 'react'
function Home() {
    return (
        <>
            <Head>
                <title>Dashboard</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Group
                grow
                sx={(theme) => ({
                    padding: theme.spacing.md,
                })}
            >
                <Stack>
                    <Group>
                        <Title order={1} sx={{ fontSize: 64 }}>
                            Dashboard
                        </Title>
                    </Group>
                    <OlViewer
                        url={`https://tf43qhrirlalypcf3vrp65iwzm0zmnmy.lambda-url.eu-west-2.on.aws/iiif/2/01GMX0QCA2MTBVMSVED7CAJ70B/info.json`}
                    />
                </Stack>
            </Group>
        </>
    )
}

Home.getLayout = function getLayout(page: ReactElement) {
    //return <LayoutShellSideNav>{page}</LayoutShellSideNav>;
    return page
}

export default Home
