import { CreateOrganisation } from "@components/organisation/organisation-create";
import { OrganisationInviteCreate } from "@components/organisation/organisation-invite/invite-create";
import { JoinOrganisation } from "@components/organisation/organisation-join";
import { OrganisationList } from "@components/organisation/organisation-list";
import { Box, Button, Group, Modal, Stack, Tabs, Title } from "@mantine/core";
import { LayoutShellSideNav } from "layouts";
import Head from "next/head";
import React, { ReactElement, useState } from "react";

const Organisations = () => {
    const [open, setOpen] = useState(false);
    return (
        <>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Stack
                sx={(theme) => ({
                    padding: theme.spacing.md,
                })}
            >
                <Stack>
                    <Group position="apart">
                        <Title order={1} sx={{ fontSize: 64 }}>
                            Organisations
                        </Title>
                        <Button onClick={() => setOpen(true)}>Add Organisation</Button>
                    </Group>
                </Stack>
                <Box>
                    <OrganisationList />
                </Box>
            </Stack>
            <Modal onClose={() => setOpen(false)} opened={open} title="Add Organisation">
                <Tabs>
                    <Tabs.List grow>
                        <Tabs.Tab value="create">Create New</Tabs.Tab>
                        <Tabs.Tab value="join">Join</Tabs.Tab>
                    </Tabs.List>
                    <Tabs.Panel value="create">
                        <CreateOrganisation onCreate={() => setOpen(false)} />
                    </Tabs.Panel>
                    <Tabs.Panel value="join">
                        <JoinOrganisation /*onJoin={() => setOpen(false)}*/ />
                    </Tabs.Panel>
                </Tabs>
            </Modal>
        </>
    );
};

Organisations.getLayout = function getLayout(page: ReactElement) {
    return <LayoutShellSideNav>{page}</LayoutShellSideNav>;
};

export default Organisations;
