import { ContentType } from "@components/contentType";
import { ContentTypeCard } from "@components/contentType/contentType-card";
import { ContentTypeCreate } from "@components/contentType/contentType-create/contentTypeCreate";
import { NavigationList } from "@components/navigation/linkList";
import { PageHeader } from "@components/ui/page-header";
import { useGetOrganisationContentTypes } from "@data/contentType/hooks";
import { faFile, faHouse, faUser } from "@fortawesome/pro-regular-svg-icons";
import { Grid, Group } from "@mantine/core";
import { LayoutShellSideNav } from "layouts";
import { GetServerSidePropsContext } from "next";
import Head from "next/head";
import React, { ReactElement } from "react";
import { params as cloudParams } from "@serverless/cloud";
import { getCookie } from "cookies-next";
import { apiClient } from "@data/config";
import { getOrganisationContentTypes } from "@data/contentType/queries";
import axios from "axios";
import camelcaseKeys from "camelcase-keys";
import { CleanedCamel } from "type-helpers";
import { ContentType as ContentTypeProps } from "@lib/contentType/data/contentType.model";

interface ContentTypePageProps {
    organisationId: string;
    initialData: { contentTypes: CleanedCamel<ContentTypeProps>[] };
}

const HomeSidebar = () => {
    return (
        <NavigationList
            items={[
                {
                    link: "/home",
                    icon: faHouse,
                    text: "Home",
                },
                {
                    link: "/forms",
                    icon: faFile,
                    text: "Content Types",
                    active: true,
                },
                {
                    link: "/users",
                    icon: faUser,
                    text: "Users",
                },
            ]}
        />
    );
};

function ContentTypePage({
    organisationId,
    initialData,
}: ContentTypePageProps) {
    const { data } = useGetOrganisationContentTypes(
        organisationId,
        initialData
    );
    console.log("initialData :>> ", initialData);
    return (
        <>
            <Head>
                <title>Organisation Content Types</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Group
                direction="column"
                grow
                spacing={0}
                sx={{ height: "100%" }}
                noWrap
            >
                <PageHeader title="Content Types">
                    <ContentTypeCreate />
                </PageHeader>
                <Grid
                    sx={(theme) => ({
                        borderTop: `1px solid ${theme.colors.dark[6]}`,
                    })}
                    gutter="md"
                    px="sm"
                    mx={0}
                >
                    <Grid.Col
                        span={3}
                        sx={(theme) => ({
                            borderRight: `1px solid ${theme.colors.dark[6]}`,
                        })}
                    >
                        <Group direction="column" grow spacing="sm">
                            {data?.contentTypes?.length
                                ? data.contentTypes.map((contentType, i) => (
                                      <ContentTypeCard
                                          key={contentType.id}
                                          contentType={contentType}
                                      />
                                  ))
                                : "No content types Found"}
                        </Group>
                    </Grid.Col>
                    <Grid.Col span={9}>
                        <ContentType />
                    </Grid.Col>
                </Grid>
            </Group>
        </>
    );
}

ContentTypePage.getLayout = (page: ReactElement) => (
    <LayoutShellSideNav
        sidebarContent={<HomeSidebar />}
        headerProps={{ title: "Content Types" }}
    >
        {page}
    </LayoutShellSideNav>
);

export async function getServerSideProps({
    params,
    req,
}: GetServerSidePropsContext<{ orgId: string }>) {
    const { orgId } = params!;
    const token = getCookie("token", { req });
    const { data } = await axios.get(
        `${cloudParams.CLOUD_URL}/organisations/${orgId}/contentTypes`,
        {
            headers: {
                "Content-type": "application/json",
                Authorization: `Bearer ${token}`,
            },
        }
    );
    return {
        props: {
            organisationId: params!.orgId,
            initialData: camelcaseKeys(data),
        },
    };
}

export default ContentTypePage;
